config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get 'pages/home', to: 'pages#home'

  resources :recipes
  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chef.rb
class Chef < ApplicationRecord
    has_many :recipes, dependent: :destroy
    has_secure_password

    validates :password, presence: true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    belongs_to :chef
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
    def new
        @c = Chef.new
    end

    def create
        @c = Chef.new(chef_params)
        if @c.save
            flash[:success] = "Chef details are saved"
  

        else
            render 'new'
        end
    end 

    def show
        @c = Chef.find(params[:id])
        
    end 

    def edit
        @c = Chef.find(params[:id])
    end

    def update
        @c = Chef.find(params[:id])
        if @c.update(chef_params)
            flash[:success] = "Your account is updated successfully"
            redirect_to chef_path(@c)

        else
            render 'edit'
        end 
    end 

    def index
        @c = Chef.paginate(page: params[:page], per_page: 2)
    end

    def destroy
        @c = Chef.find(params[:id])
        @c.destroy
        flash[:success] = "chef is destroyed alongwith recipes"
        redirect_to chefs_path
    end
    
    private 

    def chef_params
        params.require(:chef).permit(:name, :email, :password, :password_confirmation)
    end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home 
    end 
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    def index
        @rec = Recipe.paginate(page: params[:page], per_page: 2)
    end

    def show 
        @rec = Recipe.find(params[:id])
    end
 
    def new 
        @rec = Recipe.new
    end

    def create
        @rec = Recipe.new(recipe_params)
        @rec.chef = Chef.first
        if @rec.save
            flash[:success] = "recipe save successfully"
            redirect_to recipe_path(@rec)
    
        else 
            render 'new'
        end  
    end 

    def edit
        @rec = Recipe.find(params[:id])
    end

    def update
        @rec = Recipe.find(params[:id])
        if @rec.update(recipe_params)
            flash[:success] = "recipe is updated successfully"
            redirect_to recipe_path(@rec)

        else
            render 'edit'
        end 
    end

    def destroy
        Recipe.find(params[:id]).destroy
        flash[:success] = "deleted sucessfully"

    end

    private

    def recipe_params
        params.require(:recipe).permit(:name, :description)
        redirect_to recipes_path
    end
end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create 
        c = Chef.find_by(email: params[:session][:email].downcase)
        if c && c.authenticate(params[:session][:password])
            session[:chef_id] = c.id
            flash[:success] = "Successful login"
        else
            flash.now[:danger] = "Not a successful login"
            render 'new'
        end 
    end

    def destroy
        session[:chef_id] = nil
        flash[:success]= "logout successful"
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravatar_for(user, options= {size: 80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id} ?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "img_circle")
    end 
end
 

app/views/chefs/_form.html.erb
<%= form_for(@c, :html => {class: "form-horizontal", role: "form"}) do |f|%>
    
    <div class="form-group col-md-8">
      <p>
         <%= f.label :name%> <br>
         <%= f.text_field :name%>
      </p>

      <p>
         <%= f.label :email%> <br>
         <%= f.email_field :email%>
         
      </p>

      <p>
         <%= f.label :password, placeholder="password"%> <br>
         <%= f.password_field :password%>
         
      </p>

      <p>
         <%= f.label :password_confirmation%> <br>
         <%= f.password_field :password_confirmation%>
         
      </p>


      <p>
           <%= f.submit "Create Account"%>
       </p>

       <p>
           <%= link_to "cancel request and go back to listing page", recipes_path%>
       </p>
     
      
    </div>


    

<% end %>

app/views/chefs/edit.html.erb
<h1 align="center">Hey Chef! Edit Account!</h1><hr>
<%= render 'form'%>

app/views/chefs/index.html.erb
<h1 align="center">all the chefs here</h1>
<%= will_paginate @c%>
<% @c.each do |c|%>
    <table class="table">
       <tr>
          <td><%= link_to gravatar_for(c), chef_path(c)%></td>
          <td><%= link_to c.name.capitalize, chef_path(c)%></td>
          <td><%= pluralize(c.recipes.count, "recipe")%></td>
          <td><%= link_to "delete chef", chef_path(c), method: :delete%></td>
         
         
       </tr>

    </table>
    
    
<% end %>  
<%= will_paginate @c%>

app/views/chefs/new.html.erb
<h1 align="center">Hey Chef! Sign Up!</h1><hr>
<%= render 'form'%>

app/views/chefs/show.html.erb
<h1 align="center">Chef <%= @c.name%>'s profile</h1>

<table class="table">
       <tr>
          <td align="center"><%= gravatar_for @c%></td>
         
       </tr>

</table>


<h2 align="center">Chef <%= @c.name%>'s recipes</h2>
<%= render 'recipes/recipe', obj: @c.recipes%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChefsWithUi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/navigation'%>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<style>
   .jumbotron {
    background-color: silver
   
    background-image: asset-url("image.jpg");
    background-size: cover;
    height: 300px;

   }


  
</style>



<div class="jumbotron center">
  <h1>Welcome Recipe Application</h1>
  <h2>The best recipe app</h2>
  <p><%= link_to "Sign up or Log in", signup_path, class: "btn btn-danger btn-lg btn-xlarge"%></p> 
</div>

app/views/recipes/_recipe.html.erb
<h1 align="center">all the recipes here</h1>

<% obj.each do |r|%>
    <table class="table">
       <tr>
          <td><%= gravatar_for(r.chef, size: 50)%></td>
          <td><%= link_to r.name, recipe_path(r)%></td>
          <td><%= truncate(r.description, length: 150)%></td>
         
       </tr>

    </table>
    
    
<% end %>  

app/views/recipes/edit.html.erb
<h1>This is a edit page</h1>
<%= form_for(@rec, :html => {class: "form-horizontal", role: "form"}) do |f|%>
    <div class="form-row">
    <div class="form-group col-md-6">
      <p>
         <%= f.label :name%> <br>
         <%= f.text_field :description%>
      </p>

      <p>
         <%= f.label :description%> <br>
         <%= f.text_area :description%>
         
      </p>

      <p>
           <%= f.submit%>
       </p>

       <p>
           <%= link_to "cancel request and go back to listing page", recipes_path%>
       </p>
     
      
    </div>


    

<% end %>

app/views/recipes/index.html.erb
<div align="center">
   <%= will_paginate @rec%>
</div>
<%= render 'recipe', obj: @rec%>  
<div align="center">
   <%= will_paginate @rec%>
</div>

app/views/recipes/new.html.erb
<%= form_for(@rec, :html => {class: "form-horizontal", role: "form"}) do |f|%>
    <div class="form-row">
    <div class="form-group col-md-6">
      <p>
         <%= f.label :name%> <br>
         <%= f.text_field :description%>
      </p>

      <p>
         <%= f.label :description%> <br>
         <%= f.text_area :description%>
         
      </p>

      <p>
           <%= f.submit%>
       </p>

       <p>
           <%= link_to "cancel request and go back to listing page", recipes_path%>
       </p>
     
      
    </div>


    

<% end %>

app/views/recipes/show.html.erb
<div class="well col-md-8 col-md-offset-2">
   <h4 class="center description">steps:</h4>
   <hr>
   <strong><%= simple_format(@rec.description)%></strong> 
   <p> 
     created by:-
   </p>
   <p class="center"> 
      <%= link_to gravatar_for(@rec.chef), recipes_path%>
   </p>

   <p class="center"> 
      
      <small><%= @rec.chef.name.capitalize%></small >
   </p>
   
   <p class="center"> 
      
      <small><%=  link_to "edit the recipt", edit_recipe_path(@rec)%></small>
   </p>

   <p class="center"> 
      
   <small><%=  link_to "delete the recipt", recipe_path(@rec), method: :delete, data: {confirm: "you sure?", "turbo-method": :delete }%></small>
   </p>
</div>   

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
           <a class="nav-link active" aria-current="page" href="#"><%= link_to "logout", logout_path, method: :delete%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#"><%= link_to "login", login_path%></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=""> <%= link_to "Chefs", chefs_path%></a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>